### ISSUE TITLE
Wrong extension for sim

### ISSUE THREAD

**Issue by vbranders** [UCLouvain-CBIO/WSBIM2122#15]
https://github.com/UCLouvain-CBIO/WSBIM2122/blob/d551f3e6bf449ce6bc36552ab760bc7e41ea180e/10-cli.Rmd#L454

should be

rm seq_1.fas sim_1.csv

And
https://github.com/UCLouvain-CBIO/WSBIM2122/blob/d551f3e6bf449ce6bc36552ab760bc7e41ea180e/10-cli.Rmd#L482

should be 

wsbim2122_data/new_dir/data/sim_100.csv

**Comment by lgatto** [comment]
Thank you!
