### ISSUE TITLE
Installing 

### ISSUE THREAD

**Issue by doujouDC** [UCLouvain-CBIO/WSBIM2122#21]
Hi Professor Louvain,

I was trying to install your packages using this in the RStudio Console:

BiocManager::install("UCLouvain-CBIO/rWSBIM2122")

and I got this error message. Any thoughts?

> BiocManager::install("UCLouvain-CBIO/rWSBIM2122")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package =
"BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.17 (BiocManager 1.30.20), R 4.3.0 (2023-04-21)
Installing github package(s) 'UCLouvain-CBIO/rWSBIM2122'
Error: package 'remotes' not installed in library path(s)
    /Users/joubertd/Library/R/arm64/4.3/library
    /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
install with 'BiocManager::install("remotes")'

Here is the page URL: https://uclouvain-cbio.github.io/WSBIM2122/index.html

**Comment by lgatto** [comment]
Install `remotes` with `install.package("remotes")` and start again. This question should have been opened in https://github.com/UCLouvain-CBIO/rWSBIM2122.
